### ISSUE TITLE
Merging resource dictionary no longer works after switching to nuget package

### ISSUE THREAD

**Issue by alexhopeoconnor** [samoatesgames/mui.extended.toolkit#1]
I can't figure out what is going on here and from a quick look through the source code and the fact my project is compiling seems to indicate I am referencing the ResourceDictionary correctly.

Basically all I have done is install the nuget package, then delete the old ResourceDictionary files from my project and update my App.xaml file to reference ModernUI.Xceed.Toolkit.xaml from this:
`<ResourceDictionary Source="/App.GUI;component/Themes/ModernUI.Xceed.Toolkit/ModernUI.Xceed.Toolkit.xaml" />`

To the following:
`<ResourceDictionary Source="/ModernUI.Xceed.Toolkit;component/Assets/ModernUI.Xceed.Toolkit.xaml" />`

I have also tried this:
`<ResourceDictionary Source="pack://application:,,,/ModernUI.Xceed.Toolkit;component/Assets/ModernUI.Xceed.Toolkit.xaml" />`

However the styles are never applied to the RichTextBox or RichTextBoxFormatBar... I am using .NET framework 4.5.2 and can actually get this working after checking out the source code and referencing the project directly and building it myself. So I think it might be an issue with the assembly in the current nuget package.

Also worth noting is that when I referenced the source project directly it complained about missing referenced for the extended WPF toolkit, so I did a nuget restore and after that it built fine and the referenced assembly worked!

Anyway just trying to get to the bottom of this one, let me know if this is not the appropriate place and I will create an SO question instead.

**Comment by samoatesgames** [comment]
Hey,

Sorry for the massive delay in response!
There is a new Nuget package, which I have just used on a new project which worked as expected.

I've also added a section to the wiki on how to setup a project for use with the Nuget package:
https://github.com/samoatesgames/mui.extended.toolkit/wiki#setting-up-muiextendedtoolkit---nuget 

If you continue to have issues let me know and i'll investigate more.
