### ISSUE TITLE
RichTextBoxFormatBar causes RichTextBox

### ISSUE THREAD

**Issue by alexhopeoconnor** [samoatesgames/mui.extended.toolkit#3]
Hello,

I have recently switched the latest version of the extended wpf tookit and am now receiving the following exception while using your styles:

> System.Windows.Markup.XamlParseException occurred
  HResult=0x80131501
  Message='Failed to create a 'DependencyProperty' from the text 'ShowAdvancedButton'.' Line number '341' and line position '41'.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.FrameworkTemplate.LoadTemplateXaml(XamlReader templateReader, XamlObjectWriter currentWriter)

> Inner Exception 1:
> NotSupportedException: DependencyPropertyConverter cannot convert from System.String.

**Comment by samoatesgames** [comment]
Closing in favor of issue: https://github.com/samoatesgames/mui.extended.toolkit/issues/4
